blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://discord.gg/unblock
    about: Please ask and answer questions here.
  - name: Heroku, Repl.it, Blocked site issues
    url: https://www.youtube.com/watch?v=BLUkgRAy_Vo
    about: Do not create issues for these.
